var Module = (() => {
  
  return (
async function(moduleArg = {}) {
  var moduleRtn;

var p=moduleArg,aa="object"==typeof window,q="undefined"!=typeof WorkerGlobalScope;p={decode(a){try{const b=r(a.length);if(0===b)throw"Memory allocation error";u.set(a,b);const [c,d,e,f]=p._decode(b,a.length);if(0!==e)throw`libheif error code ${e}`;return{data:new Uint8ClampedArray(u.subarray(f,f+c*d*4)),width:c,height:d}}finally{w()}}};var ba=import.meta.url,ca="",da,y;
if(aa||q){try{ca=(new URL(".",ba)).href}catch{}q&&(y=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});da=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}var ea=console.log.bind(console),A=console.error.bind(console),B=!1,fa,ha,C,D,u,E,F,G,H,ia,ja,ka,la,ma=!1;
function na(){var a=C.buffer;D=new Int8Array(a);E=new Int16Array(a);u=new Uint8Array(a);F=new Uint16Array(a);G=new Int32Array(a);H=new Uint32Array(a);ia=new Float32Array(a);ja=new Float64Array(a);ka=new BigInt64Array(a);la=new BigUint64Array(a)}var I=0,J=null;function oa(a){a="Aborted("+a+")";A(a);B=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ha?.(a);throw a;}var pa;
async function qa(a){try{var b=await da(a);return new Uint8Array(b)}catch{}if(y)a=y(a);else throw"both async and sync fetching of the wasm failed";return a}async function ra(a,b){try{var c=await qa(a);return await WebAssembly.instantiate(c,b)}catch(d){A(`failed to asynchronously prepare wasm: ${d}`),oa(d)}}
async function sa(a){var b=pa;if("function"==typeof WebAssembly.instantiateStreaming)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){A(`wasm streaming compile failed: ${d}`),A("falling back to ArrayBuffer instantiation")}return ra(b,a)}class ta{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var K={},ua=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};
function L(a){return this.fromWireType(H[a>>2])}
var M={},N={},O={},va=class extends Error{constructor(a){super(a);this.name="InternalError"}},wa=(a,b,c)=>{function d(g){g=c(g);if(g.length!==a.length)throw new va("Mismatched type converter count");for(var h=0;h<a.length;++h)P(a[h],g[h])}a.forEach(g=>O[g]=b);var e=Array(b.length),f=[],l=0;b.forEach((g,h)=>{N.hasOwnProperty(g)?e[h]=N[g]:(f.push(g),M.hasOwnProperty(g)||(M[g]=[]),M[g].push(()=>{e[h]=N[g];++l;l===f.length&&d(e)}))});0===f.length&&d(e)},Q=a=>{for(var b="";;){var c=u[a++];if(!c)return b;
b+=String.fromCharCode(c)}},R=class extends Error{constructor(a){super(a);this.name="BindingError"}},ya=a=>{throw new R(a);};function za(a,b,c={}){var d=b.name;if(!a)throw new R(`type "${d}" must have a positive integer typeid pointer`);if(N.hasOwnProperty(a)){if(c.N)return;throw new R(`Cannot register type '${d}' twice`);}N[a]=b;delete O[a];M.hasOwnProperty(a)&&(b=M[a],delete M[a],b.forEach(e=>e()))}function P(a,b,c={}){return za(a,b,c)}
var Aa=(a,b,c)=>{switch(b){case 1:return c?d=>D[d]:d=>u[d];case 2:return c?d=>E[d>>1]:d=>F[d>>1];case 4:return c?d=>G[d>>2]:d=>H[d>>2];case 8:return c?d=>ka[d>>3]:d=>la[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Ba=[],S=[0,1,,1,null,1,!0,1,!1,1],Ca=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Ba.pop()||S.length;S[b]=a;S[b+1]=1;return b}},Da={name:"emscripten::val",fromWireType:a=>{if(!a)throw new R(`Cannot use deleted val. handle = ${a}`);
var b=S[a];9<a&&0===--S[a+1]&&(S[a]=void 0,Ba.push(a));return b},toWireType:(a,b)=>Ca(b),I:8,readValueFromPointer:L,G:null},Ea=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(ia[c>>2])};case 8:return function(c){return this.fromWireType(ja[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Fa={ftfnn:function(a,b,c,d,e,f,l,g,h){return function(m,k){m=g.toWireType(null,m);k=h.toWireType(null,k);k=c(d,m,k);return f.fromWireType(k)}}},Ga=(a,b)=>{var c=p;if(void 0===
c[a].H){var d=c[a];c[a]=function(...e){if(!c[a].H.hasOwnProperty(e.length))throw new R(`Function '${b}' called with an invalid number of arguments (${e.length}) - expects one of (${c[a].H})!`);return c[a].H[e.length].apply(this,e)};c[a].H=[];c[a].H[d.J]=d}},Ha=(a,b,c)=>{if(p.hasOwnProperty(a)){if(void 0===c||void 0!==p[a].H&&void 0!==p[a].H[c])throw new R(`Cannot register public name '${a}' twice`);Ga(a,a);if(p[a].H.hasOwnProperty(c))throw new R(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
p[a].H[c]=b}else p[a]=b,p[a].J=c},Ia=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(H[b+4*d>>2]);return c},Ja,T=(a,b)=>{a=Q(a);var c=Ja.get(b);if("function"!=typeof c)throw new R(`unknown function pointer with signature ${a}: ${b}`);return c};class Ka extends Error{}
var Ma=a=>{a=La(a);var b=Q(a);U(a);return b},Na=(a,b)=>{function c(f){e[f]||N[f]||(O[f]?O[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Ka(`${a}: `+d.map(Ma).join([", "]));},Oa=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},V=(a,b,c)=>{var d=u;if(0<c){c=b+c-1;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);if(127>=f){if(b>=c)break;d[b++]=f}else if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6;d[b++]=128|f&63}else if(65535>=f){if(b+2>=c)break;d[b++]=224|
f>>12;d[b++]=128|f>>6&63;d[b++]=128|f&63}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63;d[b++]=128|f>>6&63;d[b++]=128|f&63;e++}}d[b]=0}},Pa=new TextDecoder,Qa=new TextDecoder("utf-16le"),Ra=(a,b)=>{a>>=1;b=a+b/2;for(var c=a;!(c>=b)&&F[c];)++c;return Qa.decode(F.subarray(a,c))},Sa=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)E[b>>1]=a.charCodeAt(e),b+=2;E[b>>1]=0;return b-d},Ta=a=>2*a.length,Ua=(a,b)=>{for(var c="",d=0;!(d>=b/4);d++){var e=
G[a+4*d>>2];if(!e)break;c+=String.fromCodePoint(e)}return c},Va=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);65535<f&&e++;G[b>>2]=f;b+=4;if(b+4>c)break}G[b>>2]=0;return b-d},Wa=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&c++,b+=4;return b},X={},Xa=a=>{if(!B)try{a()}catch(b){if(!(b instanceof ta||"unwind"==b))throw b;}},Ya=[null,[],[]],La,w,U,r,Za,ab={q:()=>{},v:()=>oa(""),o:a=>{var b=K[a];delete K[a];var c=b.elements,d=
c.length,e=c.map(g=>g.M).concat(c.map(g=>g.S)),f=b.O,l=b.P;wa([a],e,g=>{c.forEach((h,m)=>{var k=g[m],n=h.K,x=h.L,z=g[m+d],t=h.R,W=h.T;h.read=v=>k.fromWireType(n(x,v));h.write=(v,$a)=>{var xa=[];t(W,v,z.toWireType(xa,$a));ua(xa)}});return[{name:b.name,fromWireType:h=>{for(var m=Array(d),k=0;k<d;++k)m[k]=c[k].read(h);l(h);return m},toWireType:(h,m)=>{if(d!==m.length)throw new TypeError(`Incorrect number of tuple elements for ${b.name}: expected=${d}, actual=${m.length}`);for(var k=f(),n=0;n<d;++n)c[n].write(k,
m[n]);null!==h&&h.push(l,k);return k},I:8,readValueFromPointer:L,G:l}]})},e:(a,b,c,d,e)=>{b=Q(b);d=0n===d;let f=l=>l;if(d){const l=8*c;f=g=>BigInt.asUintN(l,g);e=f(e)}P(a,{name:b,fromWireType:f,toWireType:(l,g)=>{"number"==typeof g&&(g=BigInt(g));return g},I:8,readValueFromPointer:Aa(b,c,!d),G:null})},h:(a,b,c,d)=>{b=Q(b);P(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,f){return f?c:d},I:8,readValueFromPointer:function(e){return this.fromWireType(u[e])},G:null})},f:a=>P(a,Da),
d:(a,b,c)=>{b=Q(b);P(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,I:8,readValueFromPointer:Ea(b,c),G:null})},j:(a,b,c,d,e,f,l)=>{var g=Ia(b,c);a=Q(a);a=Oa(a);e=T(d,e);Ha(a,function(){Na(`Cannot call ${a} due to unbound types`,g)},b-1);wa([],g,h=>{var m=a;var k=a;h=[h[0],null].concat(h.slice(1));var n=e,x=h.length;if(2>x)throw new R("argTypes array size mismatch! Must at least get return value and 'this' types!");var z=null!==h[1]&&!1,t;a:{for(t=1;t<h.length;++t)if(null!==h[t]&&void 0===h[t].G){t=
!0;break a}t=!1}var W="void"!==h[0].name;n=[k,ya,n,f,ua,h[0],h[1]];for(var v=0;v<x-2;++v)n.push(h[v+2]);if(!t)for(v=z?1:2;v<h.length;++v)null!==h[v].G&&n.push(h[v].G);x=[z?"t":"f",W?"t":"f",l?"t":"f"];for(z=z?1:2;z<h.length;++z)t=h[z],x.push(void 0===t.G?"u":null===t.G?"n":"t");h=Fa[x.join("")](...n);k=Object.defineProperty(h,"name",{value:k});h=b-1;if(!p.hasOwnProperty(m))throw new va("Replacing nonexistent public symbol");void 0!==p[m].H&&void 0!==h?p[m].H[h]=k:(p[m]=k,p[m].J=h);return[]})},b:(a,
b,c,d,e)=>{b=Q(b);let f=g=>g;if(0===d){var l=32-8*c;f=g=>g<<l>>>l;e=f(e)}P(a,{name:b,fromWireType:f,toWireType:(g,h)=>h,I:8,readValueFromPointer:Aa(b,c,0!==d),G:null})},a:(a,b,c)=>{function d(f){return new e(D.buffer,H[f+4>>2],H[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=Q(c);P(a,{name:c,fromWireType:d,I:8,readValueFromPointer:d},{N:!0})},g:(a,b)=>{b=Q(b);P(a,{name:b,fromWireType:function(c){for(var d=
H[c>>2],e=c+4,f,l=e,g=0;g<=d;++g){var h=e+g;if(g==d||0==u[h]){if(l){for(var m=l+(h-l),k=l;!(k>=m)&&u[k];)++k;l=Pa.decode(u.subarray(l,k))}else l="";void 0===f?f=l:(f+=String.fromCharCode(0),f+=l);l=h+1}}U(c);return f},toWireType:function(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e,f="string"==typeof d;if(!(f||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new R("Cannot pass non-string to std::string");if(f)for(var l=e=0;l<d.length;++l){var g=d.charCodeAt(l);127>=g?e++:2047>=g?
e+=2:55296<=g&&57343>=g?(e+=4,++l):e+=3}else e=d.length;l=r(4+e+1);g=l+4;H[l>>2]=e;f?V(d,g,e+1):u.set(d,g);null!==c&&c.push(U,l);return l},I:8,readValueFromPointer:L,G(c){U(c)}})},c:(a,b,c)=>{c=Q(c);if(2===b){var d=Ra;var e=Sa;var f=Ta;var l=g=>F[g>>1]}else 4===b&&(d=Ua,e=Va,f=Wa,l=g=>H[g>>2]);P(a,{name:c,fromWireType:g=>{for(var h=H[g>>2],m,k=g+4,n=0;n<=h;++n){var x=g+4+n*b;if(n==h||0==l(x))k=d(k,x-k),void 0===m?m=k:(m+=String.fromCharCode(0),m+=k),k=x+b}U(g);return m},toWireType:(g,h)=>{if("string"!=
typeof h)throw new R(`Cannot pass non-string to C++ string type ${c}`);var m=f(h),k=r(4+m+b);H[k>>2]=m/b;e(h,k+4,m+b);null!==g&&g.push(U,k);return k},I:8,readValueFromPointer:L,G(g){U(g)}})},x:(a,b,c,d,e,f)=>{K[a]={name:Q(b),O:T(c,d),P:T(e,f),elements:[]}},w:(a,b,c,d,e,f,l,g,h)=>{K[a].elements.push({M:b,K:T(c,d),L:e,S:f,R:T(l,g),T:h})},i:(a,b)=>{b=Q(b);P(a,{U:!0,name:b,I:0,fromWireType:()=>{},toWireType:()=>{}})},l:()=>{},m:(a,b)=>{X[a]&&(clearTimeout(X[a].id),delete X[a]);if(!b)return 0;var c=setTimeout(()=>
{delete X[a];Xa(()=>Za(a,performance.now()))},b);X[a]={id:c,V:b};return 0},n:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();H[a>>2]=60*Math.max(f,e);G[b>>2]=Number(f!=e);b=l=>{var g=Math.abs(l);return`UTC${0<=l?"-":"+"}${String(Math.floor(g/60)).padStart(2,"0")}${String(g%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(V(a,c,17),V(b,d,17)):(V(a,d,17),V(b,c,17))},p:a=>{var b=u.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=
c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-C.buffer.byteLength+65535)/65536|0;try{C.grow(d);na();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},s:()=>52,t:()=>52,u:function(){return 70},r:(a,b,c,d)=>{for(var e=0,f=0;f<c;f++){var l=H[b>>2],g=H[b+4>>2];b+=8;for(var h=0;h<g;h++){var m=a,k=u[l+h],n=Ya[m];if(0===k||10===k){m=1===m?ea:A;for(k=0;n[k]&&!(NaN<=k);)++k;k=Pa.decode(n.buffer?n.subarray(0,k):new Uint8Array(n.slice(0,
k)));m(k);n.length=0}else n.push(k)}e+=g}H[d>>2]=e;return 0},k:a=>{throw new ta(a);}},Y=await (async function(){I++;var a={a:ab};pa??=p.locateFile?ca+"Heic-D-Code.wasm":(new URL("Heic-D-Code.wasm",import.meta.url)).href;Y=(await sa(a)).instance.exports;C=Y.y;na();Ja=Y.E;a=Y;La=a.A;w=a.B;U=a.C;r=a.D;Za=a.F;I--;0==I&&J&&(a=J,J=null,a());return Y}());function Z(){0<I?J=Z:0<I?J=Z:(p.calledRun=!0,B||(ma=!0,Y.z(),fa?.(p)))}Z();ma?moduleRtn=p:moduleRtn=new Promise((a,b)=>{fa=a;ha=b});


  return moduleRtn;
}
);
})();
export default Module;
